"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
linemode    = "size"
show_hidden = false
sort_by     = "natural"

[preview]
tab_size   = 2
max_width  = 1000
max_height = 1000

[opener]
edit = [
    { run = '${EDITOR:=vi} "$@"', desc = "$EDITOR", block = true },
    { run = 'code "$@"', orphan = true },
]
play = [
    { run = 'mpv --force-window "$@"' },
    { run = 'vlc "$@"' }
]

[plugin]
prepend_fetchers = [
	{ id = "git", url = "*", run = "git" },
	{ id = "git", url = "*/", run = "git" },
]
